In [2]:
#Declare 2D array
list1 = [1,2,3,4,5]
list2 = [5,6,7,8,9,10]

print(list1, list2)

[1, 2, 3, 4, 5] [5, 6, 7, 8, 9, 10]


In [3]:
prod = []

for i in range(len(list1)):
    print(list1[i] * list2[i])
    prod.append(list1[i] * list2[i])

print(prod)

5
12
21
32
45
[5, 12, 21, 32, 45]


In [4]:
### NumPy Basic Operations
import numpy as np

list1 = [1, 2, 3, 4, 5]
list2 = [5, 6, 7, 8, 9]

a = np.array(list1)
b = np.array(list2)

print("List 1:", list1)
print("List 2:", list2)

List 1: [1, 2, 3, 4, 5]
List 2: [5, 6, 7, 8, 9]


In [5]:

print("Array a:", a)
print("Array b:", b)

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Array a: [1 2 3 4 5]
Array b: [5 6 7 8 9]
Addition: [ 6  8 10 12 14]
Subtraction: [-4 -4 -4 -4 -4]
Multiplication: [ 5 12 21 32 45]
Division: [0.2        0.33333333 0.42857143 0.5        0.55555556]


In [6]:
print("Array:", a)
print("Type:", type(a))
print("Data type:", a.dtype)
print("Shape:", a.shape)
print("Number of dimensions:", a.ndim)
print("Size:", a.size)

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (5,)
Number of dimensions: 1
Size: 5


What each function does
np.array()      → Creates an array from existing data
np.arange()     → Creates numbers within a range
np.zeros()      → Creates an array filled with 0
np.ones()       → Creates an array filled with 1
np.linspace()   → Creates evenly spaced numbers
np.empty()      → Creates an array without initializing its values

For example:

np.arange(1, 6)

gives:

[1 2 3 4 5]

And:

np.linspace(0, 10, 5)

gives approximately:

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1:", arr1)
arr2 = np.arange(1, 6)
print("Array 2:", arr2)
arr3 = np.zeros(5)
print("Array 3:", arr3)
arr4 = np.ones(5)
print("Array 4:", arr4)
arr5 = np.linspace(0, 10, 5)
print("Array 5:", arr5)
arr6 = np.empty(5)

Array 1: [1 2 3 4 5]
Array 2: [1 2 3 4 5]
Array 3: [0. 0. 0. 0. 0.]
Array 4: [1. 1. 1. 1. 1.]
Array 5: [ 0.   2.5  5.   7.5 10. ]


#### All Matrix Operations

In [10]:
matrix = np.array([ [1, 2, 3], [4, 5, 6] ]) 
print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([])
arr6 = np.random.rand(3)
arr7 = np.random.randint(1, 10, 5)
arr8 = np.random.normal(0, 2, 3)
print("Empty array:", arr)
print("Random values:", arr6)
print("Random integers:", arr7)
print("Normal distribution:", arr8)

Empty array: []
Random values: [0.34440045 0.92786588 0.81485872]
Random integers: [6 6 2 2 4]
Normal distribution: [-1.27008209  1.98239229 -0.96468754]


What each operation does
np.eye(4) → creates a 4 × 4 identity matrix.
np.diag([1, 2, 3, 4]) → creates a 4 × 4 diagonal matrix.
np.full((3, 3), 7) → creates a 3 × 3 matrix filled with 7.

In [13]:
arr9 = np.eye(4)
arr10 = np.diag([1, 2, 3, 4])
arr11 = np.full((3, 3), 7)
print("Identity Matrix (4 x 4):")
print(arr9)
print("\nDiagonal Matrix (4 x 4):")
print(arr10)
print("\nFull Matrix (3 x 3):")
print(arr11)

Identity Matrix (4 x 4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal Matrix (4 x 4):
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Full Matrix (3 x 3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [15]:
arr = np.array([ [1, 2, 3], [4, 5, 6] ])
print("Original Matrix:")
print(arr)
arr1 = np.transpose(arr)
print("\nTranspose using np.transpose():")
print(arr1)
arr2 = arr.T
print("\nTranspose using .T:")
print(arr2)
arr3 = np.transpose(arr, axes=(1, 0))
print("\nTranspose using axes:")
print(arr3)
print("\nOriginal Shape:", arr.shape)
print("Transpose Shape:", arr1.shape)

Original Matrix:
[[1 2 3]
 [4 5 6]]

Transpose using np.transpose():
[[1 4]
 [2 5]
 [3 6]]

Transpose using .T:
[[1 4]
 [2 5]
 [3 6]]

Transpose using axes:
[[1 4]
 [2 5]
 [3 6]]

Original Shape: (2, 3)
Transpose Shape: (3, 2)


In [16]:
arr = np.array(range(1, 7)) #arr = ([1,2,3,4,5,6,7])
print("Original 1D Array:")
print(arr)
arr2 = arr.reshape(2, 3)
print("\nReshaped Array (2 x 3):")
print(arr2)

Original 1D Array:
[1 2 3 4 5 6]

Reshaped Array (2 x 3):
[[1 2 3]
 [4 5 6]]


In [17]:
arr = np.array([ [1, 2], [3, 4] ])
print(arr)
print("\nDeterminant:")
print(np.linalg.det(arr))
print("\nInverse:")
print(np.linalg.inv(arr))
eigenval, eigenvec = np.linalg.eig(arr)
print("\nEigenvalues:")
print(eigenval)
print("\nEigenvectors:")
print(eigenvec)
print("\nRank:")
print(np.linalg.matrix_rank(arr))

[[1 2]
 [3 4]]

Determinant:
-2.0000000000000004

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Rank:
2


In [19]:
### Important NumPy Indexing and Slicing Operations
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original Matrix:")
print(matrix)

# Single element
print("\nElement:")
print(matrix[0, 1])

# First row
print("\nFirst Row:")
print(matrix[0, :])

# First column
print("\nFirst Column:")
print(matrix[:, 0])

# Last column
print("\nLast Column:")
print(matrix[:, -1])

# First two rows
print("\nFirst Two Rows:")
print(matrix[0:2, :])

# First two columns
print("\nFirst Two Columns:")
print(matrix[:, 0:2])

# 2 x 2 submatrix
print("\n2 x 2 Submatrix:")
print(matrix[0:2, 0:2])

# Specific submatrix
print("\nSubmatrix:")
print(matrix[1:3, 1:3])

# Reverse rows
print("\nReverse Rows:")
print(matrix[::-1, :])

# Reverse columns
print("\nReverse Columns:")
print(matrix[:, ::-1])



Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element:
2

First Row:
[1 2 3]

First Column:
[1 4 7]

Last Column:
[3 6 9]

First Two Rows:
[[1 2 3]
 [4 5 6]]

First Two Columns:
[[1 2]
 [4 5]
 [7 8]]

2 x 2 Submatrix:
[[1 2]
 [4 5]]

Submatrix:
[[5 6]
 [8 9]]

Reverse Rows:
[[7 8 9]
 [4 5 6]
 [1 2 3]]

Reverse Columns:
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
matrix = np.array([ [1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16] ])
print("Original Matrix:")
print(matrix)

print("\nFirst Element:")
print(matrix[0, 0])

print("\nElement at Row 2, Column 3:")
print(matrix[1, 2])

print("\nFirst Row:") 
print(matrix[0, :]) 
print("\nSecond Row:") 
print(matrix[1, :]) 
print("\nAll Rows:")
print(matrix[:, :])
print("\nFirst Column:")
print(matrix[:, 0])
print("\nSecond Column:")
print(matrix[:, 1])
print("\nThird Column:")

print(matrix[:, 2])
print("\nLast Column:")
print(matrix[:, -1])
print("\nFirst 2 Rows:")
print(matrix[0:2, :])
print("\nFirst 2 Columns:")
print(matrix[:, 0:2])
print("\nSubmatrix (Rows 0-1, Columns 1-2):")
print(matrix[0:2, 1:3])
print("\nSubmatrix (Rows 1-2, Columns 1-3):")
print(matrix[1:3, 1:4])
print("\n2 x 2 Submatrix:")
print(matrix[0:2, 0:2])
print("\nLast 2 Rows and Last 2 Columns:")
print(matrix[2:4, 2:4])
print("\nReverse Rows:")
print(matrix[::-1, :])
print("\nReverse Columns:")
print(matrix[:, ::-1])
print("\nReverse Entire Matrix:")
print(matrix[::-1, ::-1])

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First Element:
1

Element at Row 2, Column 3:
7

First Row:
[1 2 3 4]

Second Row:
[5 6 7 8]

All Rows:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First Column:
[ 1  5  9 13]

Second Column:
[ 2  6 10 14]

Third Column:
[ 3  7 11 15]

Last Column:
[ 4  8 12 16]

First 2 Rows:
[[1 2 3 4]
 [5 6 7 8]]

First 2 Columns:
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]

Submatrix (Rows 0-1, Columns 1-2):
[[2 3]
 [6 7]]

Submatrix (Rows 1-2, Columns 1-3):
[[ 6  7  8]
 [10 11 12]]

2 x 2 Submatrix:
[[1 2]
 [5 6]]

Last 2 Rows and Last 2 Columns:
[[11 12]
 [15 16]]

Reverse Rows:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

Reverse Columns:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

Reverse Entire Matrix:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [20]:
#Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original Array:")
print(arr)
# Elements greater than 5
print("\nGreater than 5:")
print(arr[arr > 5])
# Elements less than 5
print("\nLess than 5:")
print(arr[arr < 5])

# Elements equal to 5
print("\nEqual to 5:")
print(arr[arr == 5])
# Elements greater than or equal to 5
print("\nGreater than or equal to 5:")
print(arr[arr >= 5])
# Even numbers
print("\nEven Numbers:")
print(arr[arr % 2 == 0])
# Odd numbers
print("\nOdd Numbers:")
print(arr[arr % 2 != 0])
# Numbers between 3 and 8
print("\nNumbers between 3 and 8:")
print(arr[(arr >= 3) & (arr <= 8)])
# Numbers less than 3 or greater than 8
print("\nLess than 3 or greater than 8:")
print(arr[(arr < 3) | (arr > 8)])
# Replace values using boolean indexing arr[arr > 5] = 0
print("\nAfter replacing values greater than 5 with 0:")
print(arr)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

Greater than 5:
[ 6  7  8  9 10]

Less than 5:
[1 2 3 4]

Equal to 5:
[5]

Greater than or equal to 5:
[ 5  6  7  8  9 10]

Even Numbers:
[ 2  4  6  8 10]

Odd Numbers:
[1 3 5 7 9]

Numbers between 3 and 8:
[3 4 5 6 7 8]

Less than 3 or greater than 8:
[ 1  2  9 10]

After replacing values greater than 5 with 0:
[ 1  2  3  4  5  6  7  8  9 10]
