Problem 1. 
Make a numpy array and print it

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


Problem 2. Temperature Analysis
The temperatures recorded over seven days are:
[32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0]
Store the values in a NumPy array.
Determine:
• Average temperature
• Maximum temperature
• Minimum temperature
• Day with the highest temperature
• All temperatures above the average
Write a function that accepts the temperature array and returns the required analysis.

In [5]:
temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])
print(temperatures)

average = np.mean(temperatures)
print(average)
maximum = np.max(temperatures)
print(maximum)
minimum = np.min(temperatures)
print(minimum)
day = np.argmax(temperatures)
print(day)
day = np.argmax(temperatures) + 1
print(day)
above_average = temperatures[temperatures > average]
print(above_average)

[32.5 31.8 30.2 33.1 34.5 29.8 31. ]
31.842857142857145
34.5
29.8
4
5
[32.5 33.1 34.5]


In [6]:
def temperatures_analysis(temperatures):
    average = np.mean(temperatures)
    maximum = np.max(temperatures)
    minimum = np.min(temperatures)
    highest_day = np.argmax(temperatures) + 1
    above_average = temperatures[temperatures > average]
    
    return average, maximum, minimum, highest_day, above_average

temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

average, maximum, minimum, highest_day, above_average = temperatures_analysis(temperatures)

print("Average Temperature:", average)
print("Maximum Temperature:", maximum)
print("Minimum Temperature:", minimum)
print("Day with Highest Temperature:", highest_day)
print("Temperatures Above Average:", above_average)

Average Temperature: 31.842857142857145
Maximum Temperature: 34.5
Minimum Temperature: 29.8
Day with Highest Temperature: 5
Temperatures Above Average: [32.5 33.1 34.5]


### Problem 3. Working with a Matrix
Create the following NumPy array:

1 2 3 4
5 6 7 8
9 10 11 12

Without creating another matrix manually, extract:
• The first row
• The last row
• The first column
• The last column
• The middle 2 × 2 section
• Every alternate element

Also determine its shape, number of dimensions, and total number of elements.

In [14]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original Matrix: ")
print(matrix)

print("\nFirst row:")
print(matrix[0, :])

print("\nLast row")
print(matrix[-1, :])

print("\nFirst column: ")
print(matrix[:, 0])

print("\nLast column: ")
print(matrix[:, -1])

print("\nMiddle 2*2 section: ")
print(matrix[1:3, 1:3])

print("\nEvery alternate elements:")
print(matrix.flatten()[::2])

print("\nShape:")
print(matrix.shape)

print("Number of dimentions:")
print(matrix.ndim)

print("\nTotal number of elements:")
print(matrix.size)


Original Matrix: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]

Last row
[ 9 10 11 12]

First column: 
[1 5 9]

Last column: 
[ 4  8 12]

Middle 2*2 section: 
[[ 6  7]
 [10 11]]

Every alternate elements:
[ 1  3  5  7  9 11]

Shape:
(3, 4)
Number of dimentions:
2

Total number of elements:
12


#### Problem4.EvenandOddNumbers 
Generateanarraycontainingtheintegersfrom1to50slelctedrandomly. 
Createtwonewarrays: 1Python Programming Class Assignment 2 • One containing only even numbers • One containing only odd numbers Do this using NumPy operations rather than manually constructing the arrays.

In [ ]:
# numbers = np.arange(1,51)
numbers = np.random.permutation(np.arange(1,51))
#np.random.permutation() → puts them in random order

even_numbers = numbers[numbers%2 == 0]
odd_numbers = numbers[numbers%2 != 0]

print("Original Array")
print(numbers)

print("\nEven numbers")
print(even_numbers)

print("\nOdd numbers")
print(odd_numbers)



Original Array
[29 21  1 13 38 15 41 25  2 30 45 33  4 32  6 20 28 48 27 36 26 37 34 43
 17  3 18 11 44 40 10  5  7 47 24 16 19  9 22 14 35 39 42 49 31 50 23  8
 46 12]

Even numbers
[38  2 30  4 32  6 20 28 48 36 26 34 18 44 40 10 24 16 22 14 42 50  8 46
 12]

Odd numbers
[29 21  1 13 15 41 25 45 33 27 37 43 17  3 11  5  7 47 19  9 35 39 49 31
 23]


#### Problem 5. Numbers Above a Threshold 
Generate 30 random integers between 1 and 100. Write a program that: • Displays the generated array • Finds all values greater than 50 • Finds all values between 25 and 75 • Counts how many values are greater than 50 • Calculates the average of the values greater than 50

In [22]:
numbers = np.random.permutation(np.arange(1,101))

print("Original array")
print(numbers)

Original array
[ 24  85  59  28  91  41  56  37  54  83  67  96  20  29  92  84  73  15
  49   2  47  60  11  71  44  77  58  63  87  12  10  48  46  75  34  33
  98  76  53  21  52  82   4  19  51  95   5  36  57  26  90  93  80  74
   7  13  18  66   1  42  14  17  99  38  64   6  31  62  43  79   3  81
  27  39  68  97  16 100  25  94  69  32  35  78  30  88   8  70  22  61
  23  55  50  89   9  72  86  40  45  65]


### Problem 6. Student Performance Matrix
 Consider five students and three subjects: Mathematics Physics Programming Student 1 Student 2 Student 3 Student 4 Student 5 78 65 92 56 84 82 74 88 69 90 91 80 95 72 87 Store only the numerical marks in a NumPy array. Determine: • Average marks of each student • Average marks in each subject • Highest mark in the entire dataset • Lowest mark in the entire dataset • Student with the highest average • Subject with the highest average

### Problem 7. Matrix Operations
 Create two 3×3 NumPy matrices. Perform: • Addition • Subtraction • Element-wise multiplication • Matrix multiplication Compare the results of element-wise multiplication and matrix multiplication. In your explanation, describe why the two operations produce different results.

### Problem 8. Scientific Data Transformation
 Suppose an experiment produces the following measurements: [2, 4, 6, 8, 10, 12] 2Python Programming Class Assignment 2 Create a NumPy array and calculate: • The square of every measurement • The square root of every measurement • The exponential of every measurement Then calculate the mean of the transformed data. Write your solution as a function that accepts an array as input.

### Problem 9. Reshaping Experimental Data
 Generate the numbers from 1 to 24 using NumPy. Reshape the resulting array into: • A4×6array • A6×4array • A2×3×4array Display the shape of each resulting array. Then convert the 4 ×6 array back into a one-dimensional array.

### Problem 10. Data Combination
 Create two NumPy arrays representing measurements from two experiments. For example: experiment_1 = [10, 20, 30, 40, 50] experiment_2 = [15, 25, 35, 45, 55] Combine the data in different ways so that you can obtain: • Asingle one-dimensional array containing all measurements • Amatrix where the two experiments form separate rows • Amatrix where the two experiments form separate columns Determine the shape of each result.

### Problem 11. Simple Data Cleaning
 Consider the following experimental measurements: [10, 12, 15, 200, 13, 11, 14, 250, 12, 15] Assume that values greater than 100 are invalid measurements. Write a program that: • Identifies the invalid measurements • Extracts only the valid measurements • Calculates the mean of the valid measurements • Calculates the minimum and maximum valid measurements Do not modify the original array.

### Problem 12. Image-like Matrix
 Consider the following matrix: 
 image = np.array([ [0, 0, 0, 255, 255], [0, 0, 128, 255, 255], [0, 128, 128, 128, 255], [0, 0, 128, 0, 0], [255, 0, 0, 0, 255] ]) Treat the values as pixel intensities. Determine: • Minimum pixel intensity • Maximum pixel intensity • Mean pixel intensity • Number of pixels with intensity greater than 100 • All pixels with intensity equal to 255 Then create a new array containing only pixels with intensity greater than 100.

### Problem 13. Experiment Comparison
 Two experiments produced the following measurements: experiment_A = [12, 15, 14, 18, 20, 17, 16] experiment_B = [10, 13, 15, 16, 19, 21, 18] Using NumPy, determine: • Mean of each experiment • Standard deviation of each experiment • Maximum value of each experiment • Minimum value of each experiment • Difference between the two experiments for each measurement Determine which experiment shows greater variation in its measurements.

### Problem 14. Mini Data Analysis Challenge
 Generate a 10×5 NumPy array representing measurements collected from 10 experiments across 5 variables. The values should be randomly generated. Your program should: • Display the dataset • Display its shape and dimensions • Calculate the mean of each variable • Calculate the mean of each experiment • Find the maximum and minimum value in the entire dataset • Identify all values above the overall mean • Reshape the data into a different valid shape • Flatten the reshaped data back into one dimension Organize your solution using at least two functions. 4

### Problem 15. Final Challenge: Student Performance Analysis
 Create a complete student performance analysis program. Consider: • 10 students • 4 subjects • Marks between 0 and 100 Generate the marks using NumPy. Your program should: (a) Store the marks in a two-dimensional NumPy array. (b) Calculate the average mark of every student. (c) Calculate the average mark of every subject. (d) Identify the student with the highest average. (e) Identify the student with the lowest average. (f) Identify the highest mark obtained in the entire dataset. (g) Identify the lowest mark obtained in the entire dataset. (h) Count how many students have an average above 75. (i) Extract all marks greater than 90. (j) Assign a grade to each student’s average using conditional statements. (k) Store the final student information in an appropriate Python data structure. (l) Write functions wherever appropriate. The final output should present the analysis in a clear and readable format.