Problem 1. 
Make a numpy array and print it

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


Problem 2. Temperature Analysis
The temperatures recorded over seven days are:
[32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0]
Store the values in a NumPy array.
Determine:
• Average temperature
• Maximum temperature
• Minimum temperature
• Day with the highest temperature
• All temperatures above the average
Write a function that accepts the temperature array and returns the required analysis.

In [5]:
temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])
print(temperatures)

average = np.mean(temperatures)
print(average)
maximum = np.max(temperatures)
print(maximum)
minimum = np.min(temperatures)
print(minimum)
day = np.argmax(temperatures)
print(day)
day = np.argmax(temperatures) + 1
print(day)
above_average = temperatures[temperatures > average]
print(above_average)

[32.5 31.8 30.2 33.1 34.5 29.8 31. ]
31.842857142857145
34.5
29.8
4
5
[32.5 33.1 34.5]


In [6]:
def temperatures_analysis(temperatures):
    average = np.mean(temperatures)
    maximum = np.max(temperatures)
    minimum = np.min(temperatures)
    highest_day = np.argmax(temperatures) + 1
    above_average = temperatures[temperatures > average]
    
    return average, maximum, minimum, highest_day, above_average

temperatures = np.array([32.5, 31.8, 30.2, 33.1, 34.5, 29.8, 31.0])

average, maximum, minimum, highest_day, above_average = temperatures_analysis(temperatures)

print("Average Temperature:", average)
print("Maximum Temperature:", maximum)
print("Minimum Temperature:", minimum)
print("Day with Highest Temperature:", highest_day)
print("Temperatures Above Average:", above_average)

Average Temperature: 31.842857142857145
Maximum Temperature: 34.5
Minimum Temperature: 29.8
Day with Highest Temperature: 5
Temperatures Above Average: [32.5 33.1 34.5]


### Problem 3. Working with a Matrix
Create the following NumPy array:

1 2 3 4
5 6 7 8
9 10 11 12

Without creating another matrix manually, extract:
• The first row
• The last row
• The first column
• The last column
• The middle 2 × 2 section
• Every alternate element

Also determine its shape, number of dimensions, and total number of elements.

In [6]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original Matrix: ")
print(matrix)

print("\nFirst row:")
print(matrix[0, :])

print("\nLast row")
print(matrix[-1, :])

print("\nFirst column: ")
print(matrix[:, 0])

print("\nLast column: ")
print(matrix[:, -1])

print("\nMiddle 2*2 section: ")
print(matrix[1:3, 1:3])

print("\nEvery alternate elements:")
print(matrix.flatten()[::2])

print("\nShape:")
print(matrix.shape)

print("Number of dimentions:")
print(matrix.ndim)

print("\nTotal number of elements:")
print(matrix.size)


Original Matrix: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]

Last row
[ 9 10 11 12]

First column: 
[1 5 9]

Last column: 
[ 4  8 12]

Middle 2*2 section: 
[[ 6  7]
 [10 11]]

Every alternate elements:
[ 1  3  5  7  9 11]

Shape:
(3, 4)
Number of dimentions:
2

Total number of elements:
12


#### Problem4.EvenandOddNumbers 
Generateanarraycontainingtheintegersfrom1to50slelctedrandomly. 
Createtwonewarrays: 1Python Programming Class Assignment 2 • One containing only even numbers • One containing only odd numbers Do this using NumPy operations rather than manually constructing the arrays.

In [7]:
# numbers = np.arange(1,51)
numbers = np.random.permutation(np.arange(1,51))
#np.random.permutation() → puts them in random order

even_numbers = numbers[numbers%2 == 0]
odd_numbers = numbers[numbers%2 != 0]

print("Original Array")
print(numbers)

print("\nEven numbers")
print(even_numbers)

print("\nOdd numbers")
print(odd_numbers)



Original Array
[31 16 13 50 46 33 32 27 24  8 25 18 41  2 11 47  3 15 48  9 35 14 21 39
 37  4 34 44 10 49 29 45 43 36 40 30 23  7  1 28 20 19 26 38  5 42  6 22
 17 12]

Even numbers
[16 50 46 32 24  8 18  2 48 14  4 34 44 10 36 40 30 28 20 26 38 42  6 22
 12]

Odd numbers
[31 13 33 27 25 41 11 47  3 15  9 35 21 39 37 49 29 45 43 23  7  1 19  5
 17]


#### Problem 5. Numbers Above a Threshold 
Generate 30 random integers between 1 and 100. Write a program that: • Displays the generated array • Finds all values greater than 50 • Finds all values between 25 and 75 • Counts how many values are greater than 50 • Calculates the average of the values greater than 50

In [8]:
numbers = np.random.randint(1, 101, 30)

greater_than_50 = numbers[numbers > 50]

between_25_75 = numbers[(numbers >= 25) & (numbers <= 75)]

count_greater_than_50 = np.sum(numbers > 50)

average_greater_than_50 = np.mean(greater_than_50)

print("Generated Array:")
print(numbers)

print("\nValues Greater Than 50:")
print(greater_than_50)

print("\nValues Between 25 and 75:")
print(between_25_75)

print("\nCount of Values Greater Than 50:")
print(count_greater_than_50)

print("\nAverage of Values Greater Than 50:")
print(average_greater_than_50)

Generated Array:
[20 51 26 62 65 22 95 96 68 76 79 56 82 76  4 61 25 26 43 17 23  3 72 49
 54  4 75 21 66 18]

Values Greater Than 50:
[51 62 65 95 96 68 76 79 56 82 76 61 72 54 75 66]

Values Between 25 and 75:
[51 26 62 65 68 56 61 25 26 43 72 49 54 75 66]

Count of Values Greater Than 50:
16

Average of Values Greater Than 50:
70.875


### Problem 6. Student Performance Matrix
 Consider five students and three subjects: Mathematics Physics Programming Student 1 Student 2 Student 3 Student 4 Student 5 78 65 92 56 84 82 74 88 69 90 91 80 95 72 87 Store only the numerical marks in a NumPy array. Determine: • Average marks of each student • Average marks in each subject • Highest mark in the entire dataset • Lowest mark in the entire dataset • Student with the highest average • Subject with the highest average

In [9]:
marks = np.array([
    [78, 82, 91],
    [65, 74, 80],
    [92, 88, 95],
    [56, 69, 72],
    [84, 90, 87]
])

student_averages = np.mean(marks, axis=1)

subject_averages = np.mean(marks, axis=0)

highest_mark = np.max(marks)

lowest_mark = np.min(marks)

highest_student = np.argmax(student_averages) + 1

highest_subject = np.argmax(subject_averages)

subjects = ["Mathematics", "Physics", "Programming"]

print("Marks Matrix:")
print(marks)

print("\nAverage Marks of Each Student:")
print(student_averages)

print("\nAverage Marks in Each Subject:")
print(subject_averages)

print("\nHighest Mark in the Dataset:")
print(highest_mark)

print("\nLowest Mark in the Dataset:")
print(lowest_mark)

print("\nStudent with the Highest Average:")
print("Student", highest_student)

print("\nSubject with the Highest Average:")
print(subjects[highest_subject])

Marks Matrix:
[[78 82 91]
 [65 74 80]
 [92 88 95]
 [56 69 72]
 [84 90 87]]

Average Marks of Each Student:
[83.66666667 73.         91.66666667 65.66666667 87.        ]

Average Marks in Each Subject:
[75.  80.6 85. ]

Highest Mark in the Dataset:
95

Lowest Mark in the Dataset:
56

Student with the Highest Average:
Student 3

Subject with the Highest Average:
Programming


### Problem 7. Matrix Operations
 Create two 3×3 NumPy matrices. Perform: • Addition • Subtraction • Element-wise multiplication • Matrix multiplication Compare the results of element-wise multiplication and matrix multiplication. In your explanation, describe why the two operations produce different results.

In [10]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

addition = A + B
print("\nAddition:")
print(addition)

subtraction = A - B
print("\nSubtraction:")
print(subtraction)

element_wise = A * B
print("\nElement-wise Multiplication:")
print(element_wise)

matrix_multiplication = A @ B
print("\nMatrix Multiplication:")
print(matrix_multiplication)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### Problem 8. Scientific Data Transformation
 Suppose an experiment produces the following measurements: [2, 4, 6, 8, 10, 12] 2Python Programming Class Assignment 2 Create a NumPy array and calculate: • The square of every measurement • The square root of every measurement • The exponential of every measurement Then calculate the mean of the transformed data. Write your solution as a function that accepts an array as input.

In [11]:
def scientific_data_transformation(array):
    squares = np.square(array)
    square_roots = np.sqrt(array)
    exponentials = np.exp(array)

    square_mean = np.mean(squares)
    square_root_mean = np.mean(square_roots)
    exponential_mean = np.mean(exponentials)

    return squares, square_roots, exponentials, square_mean, square_root_mean, exponential_mean


measurements = np.array([2, 4, 6, 8, 10, 12])

squares, square_roots, exponentials, square_mean, square_root_mean, exponential_mean = scientific_data_transformation(measurements)

print("Original Measurements:")
print(measurements)

print("\nSquare of Every Measurement:")
print(squares)

print("\nSquare Root of Every Measurement:")
print(square_roots)

print("\nExponential of Every Measurement:")
print(exponentials)

print("\nMean of Squares:")
print(square_mean)

print("\nMean of Square Roots:")
print(square_root_mean)

print("\nMean of Exponentials:")
print(exponential_mean)

Original Measurements:
[ 2  4  6  8 10 12]

Square of Every Measurement:
[  4  16  36  64 100 144]

Square Root of Every Measurement:
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162]

Exponential of Every Measurement:
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04 1.62754791e+05]

Mean of Squares:
60.666666666666664

Mean of Square Roots:
2.5530849508680995

Mean of Exponentials:
31371.271866746192


### Problem 9. Reshaping Experimental Data
 Generate the numbers from 1 to 24 using NumPy. Reshape the resulting array into: • A4×6array • A6×4array • A2×3×4array Display the shape of each resulting array. Then convert the 4 ×6 array back into a one-dimensional array.

In [12]:
numbers = np.arange(1, 25)

array_4x6 = numbers.reshape(4, 6)

array_6x4 = numbers.reshape(6, 4)

array_2x3x4 = numbers.reshape(2, 3, 4)

print("Original Array:")
print(numbers)

print("\n4 x 6 Array:")
print(array_4x6)

print("Shape:", array_4x6.shape)

print("\n6 x 4 Array:")
print(array_6x4)

print("Shape:", array_6x4.shape)

print("\n2 x 3 x 4 Array:")
print(array_2x3x4)

print("Shape:", array_2x3x4.shape)

one_dimensional = array_4x6.flatten()

print("\n4 x 6 Array Converted Back to 1D:")
print(one_dimensional)

print("Shape:", one_dimensional.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

4 x 6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

6 x 4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)

2 x 3 x 4 Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)

4 x 6 Array Converted Back to 1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)


### Problem 10. Data Combination
 Create two NumPy arrays representing measurements from two experiments. For example: experiment_1 = [10, 20, 30, 40, 50] experiment_2 = [15, 25, 35, 45, 55] Combine the data in different ways so that you can obtain: • Asingle one-dimensional array containing all measurements • Amatrix where the two experiments form separate rows • Amatrix where the two experiments form separate columns Determine the shape of each result.

In [13]:
import numpy as np

experiment_1 = np.array([10, 20, 30, 40, 50])
experiment_2 = np.array([15, 25, 35, 45, 55])

all_measurements = np.concatenate((experiment_1, experiment_2))

row_matrix = np.vstack((experiment_1, experiment_2))

column_matrix = np.column_stack((experiment_1, experiment_2))

print("Experiment 1:")
print(experiment_1)

print("\nExperiment 2:")
print(experiment_2)

print("\nAll Measurements:")
print(all_measurements)

print("Shape:", all_measurements.shape)

print("\nExperiments as Separate Rows:")
print(row_matrix)

print("Shape:", row_matrix.shape)

print("\nExperiments as Separate Columns:")
print(column_matrix)

print("Shape:", column_matrix.shape)

Experiment 1:
[10 20 30 40 50]

Experiment 2:
[15 25 35 45 55]

All Measurements:
[10 20 30 40 50 15 25 35 45 55]
Shape: (10,)

Experiments as Separate Rows:
[[10 20 30 40 50]
 [15 25 35 45 55]]
Shape: (2, 5)

Experiments as Separate Columns:
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
Shape: (5, 2)


### Problem 11. Simple Data Cleaning
 Consider the following experimental measurements: [10, 12, 15, 200, 13, 11, 14, 250, 12, 15] Assume that values greater than 100 are invalid measurements. Write a program that: • Identifies the invalid measurements • Extracts only the valid measurements • Calculates the mean of the valid measurements • Calculates the minimum and maximum valid measurements Do not modify the original array.

In [14]:
measurements = np.array([10, 12, 15, 200, 13, 11, 14, 250, 12, 15])

invalid = measurements[measurements > 100]

valid = measurements[measurements <= 100]

mean_valid = np.mean(valid)

minimum_valid = np.min(valid)

maximum_valid = np.max(valid)

print("Original Measurements:")
print(measurements)

print("\nInvalid Measurements:")
print(invalid)

print("\nValid Measurements:")
print(valid)

print("\nMean of Valid Measurements:")
print(mean_valid)

print("\nMinimum Valid Measurement:")
print(minimum_valid)

print("\nMaximum Valid Measurement:")
print(maximum_valid)

print("\nOriginal Array After Cleaning:")
print(measurements)

Original Measurements:
[ 10  12  15 200  13  11  14 250  12  15]

Invalid Measurements:
[200 250]

Valid Measurements:
[10 12 15 13 11 14 12 15]

Mean of Valid Measurements:
12.75

Minimum Valid Measurement:
10

Maximum Valid Measurement:
15

Original Array After Cleaning:
[ 10  12  15 200  13  11  14 250  12  15]


### Problem 12. Image-like Matrix
 Consider the following matrix: 
 image = np.array([ [0, 0, 0, 255, 255], [0, 0, 128, 255, 255], [0, 128, 128, 128, 255], [0, 0, 128, 0, 0], [255, 0, 0, 0, 255] ]) Treat the values as pixel intensities. Determine: • Minimum pixel intensity • Maximum pixel intensity • Mean pixel intensity • Number of pixels with intensity greater than 100 • All pixels with intensity equal to 255 Then create a new array containing only pixels with intensity greater than 100.

In [15]:
image = np.array([
    [0, 0, 0, 255, 255],
    [0, 0, 128, 255, 255],
    [0, 128, 128, 128, 255],
    [0, 0, 128, 0, 0],
    [255, 0, 0, 0, 255]
])

minimum_intensity = np.min(image)

maximum_intensity = np.max(image)

mean_intensity = np.mean(image)

pixels_greater_than_100 = np.sum(image > 100)

pixels_equal_to_255 = image[image == 255]

new_array = image[image > 100]

print("Image:")
print(image)

print("\nMinimum Pixel Intensity:")
print(minimum_intensity)

print("\nMaximum Pixel Intensity:")
print(maximum_intensity)

print("\nMean Pixel Intensity:")
print(mean_intensity)

print("\nNumber of Pixels Greater Than 100:")
print(pixels_greater_than_100)

print("\nPixels Equal To 255:")
print(pixels_equal_to_255)

print("\nNew Array With Pixels Greater Than 100:")
print(new_array)

Image:
[[  0   0   0 255 255]
 [  0   0 128 255 255]
 [  0 128 128 128 255]
 [  0   0 128   0   0]
 [255   0   0   0 255]]

Minimum Pixel Intensity:
0

Maximum Pixel Intensity:
255

Mean Pixel Intensity:
97.0

Number of Pixels Greater Than 100:
12

Pixels Equal To 255:
[255 255 255 255 255 255 255]

New Array With Pixels Greater Than 100:
[255 255 128 255 255 128 128 128 255 128 255 255]


### Problem 13. Experiment Comparison
 Two experiments produced the following measurements: experiment_A = [12, 15, 14, 18, 20, 17, 16] experiment_B = [10, 13, 15, 16, 19, 21, 18] Using NumPy, determine: • Mean of each experiment • Standard deviation of each experiment • Maximum value of each experiment • Minimum value of each experiment • Difference between the two experiments for each measurement Determine which experiment shows greater variation in its measurements.

### Problem 14. Mini Data Analysis Challenge
 Generate a 10×5 NumPy array representing measurements collected from 10 experiments across 5 variables. The values should be randomly generated. Your program should: • Display the dataset • Display its shape and dimensions • Calculate the mean of each variable • Calculate the mean of each experiment • Find the maximum and minimum value in the entire dataset • Identify all values above the overall mean • Reshape the data into a different valid shape • Flatten the reshaped data back into one dimension Organize your solution using at least two functions. 4

In [16]:
def analyze_data(data):
    print("Dataset:")
    print(data)

    print("\nShape:")
    print(data.shape)

    print("\nNumber of Dimensions:")
    print(data.ndim)

    variable_means = np.mean(data, axis=0)
    experiment_means = np.mean(data, axis=1)

    maximum = np.max(data)
    minimum = np.min(data)

    overall_mean = np.mean(data)
    above_mean = data[data > overall_mean]

    print("\nMean of Each Variable:")
    print(variable_means)

    print("\nMean of Each Experiment:")
    print(experiment_means)

    print("\nMaximum Value:")
    print(maximum)

    print("\nMinimum Value:")
    print(minimum)

    print("\nOverall Mean:")
    print(overall_mean)

    print("\nValues Above Overall Mean:")
    print(above_mean)


def reshape_data(data):
    reshaped_data = data.reshape(5, 10)

    print("\nReshaped Data (5 x 10):")
    print(reshaped_data)

    print("\nShape of Reshaped Data:")
    print(reshaped_data.shape)

    flattened_data = reshaped_data.flatten()

    print("\nFlattened Data:")
    print(flattened_data)

    print("\nShape of Flattened Data:")
    print(flattened_data.shape)


data = np.random.randint(1, 101, (10, 5))

analyze_data(data)

reshape_data(data)

Dataset:
[[ 64  87  48  33  72]
 [ 25  74 100  51  53]
 [ 83  21  17  34  78]
 [ 26   7  11  22  76]
 [ 88  80   3  38  49]
 [ 32   6  30  71  58]
 [ 82  38  86  68  17]
 [ 77  27  71  25  66]
 [ 24  44  52   4  29]
 [ 57  61  59  30  46]]

Shape:
(10, 5)

Number of Dimensions:
2

Mean of Each Variable:
[55.8 44.5 47.7 37.6 54.4]

Mean of Each Experiment:
[60.8 60.6 46.6 28.4 51.6 39.4 58.2 53.2 30.6 50.6]

Maximum Value:
100

Minimum Value:
3

Overall Mean:
48.0

Values Above Overall Mean:
[ 64  87  72  74 100  51  53  83  78  76  88  80  49  71  58  82  86  68
  77  71  66  52  57  61  59]

Reshaped Data (5 x 10):
[[ 64  87  48  33  72  25  74 100  51  53]
 [ 83  21  17  34  78  26   7  11  22  76]
 [ 88  80   3  38  49  32   6  30  71  58]
 [ 82  38  86  68  17  77  27  71  25  66]
 [ 24  44  52   4  29  57  61  59  30  46]]

Shape of Reshaped Data:
(5, 10)

Flattened Data:
[ 64  87  48  33  72  25  74 100  51  53  83  21  17  34  78  26   7  11
  22  76  88  80   3  38  49  32   6 

### Problem 15. Final Challenge: Student Performance Analysis
 Create a complete student performance analysis program. Consider: • 10 students • 4 subjects • Marks between 0 and 100 Generate the marks using NumPy. Your program should: (a) Store the marks in a two-dimensional NumPy array. (b) Calculate the average mark of every student. (c) Calculate the average mark of every subject. (d) Identify the student with the highest average. (e) Identify the student with the lowest average. (f) Identify the highest mark obtained in the entire dataset. (g) Identify the lowest mark obtained in the entire dataset. (h) Count how many students have an average above 75. (i) Extract all marks greater than 90. (j) Assign a grade to each student’s average using conditional statements. (k) Store the final student information in an appropriate Python data structure. (l) Write functions wherever appropriate. The final output should present the analysis in a clear and readable format.

In [17]:
import numpy as np


def calculate_grade(average):
    if average >= 90:
        return "A"
    elif average >= 80:
        return "B"
    elif average >= 70:
        return "C"
    elif average >= 60:
        return "D"
    else:
        return "F"


def analyze_performance(marks):
    student_averages = np.mean(marks, axis=1)
    subject_averages = np.mean(marks, axis=0)

    highest_student = np.argmax(student_averages)
    lowest_student = np.argmin(student_averages)

    highest_mark = np.max(marks)
    lowest_mark = np.min(marks)

    students_above_75 = np.sum(student_averages > 75)

    marks_above_90 = marks[marks > 90]

    student_information = []

    for i in range(len(student_averages)):
        grade = calculate_grade(student_averages[i])

        student = {
            "student": i + 1,
            "average": student_averages[i],
            "grade": grade
        }

        student_information.append(student)

    return (
        student_averages,
        subject_averages,
        highest_student,
        lowest_student,
        highest_mark,
        lowest_mark,
        students_above_75,
        marks_above_90,
        student_information
    )


marks = np.random.randint(0, 101, (10, 4))

(
    student_averages,
    subject_averages,
    highest_student,
    lowest_student,
    highest_mark,
    lowest_mark,
    students_above_75,
    marks_above_90,
    student_information
) = analyze_performance(marks)


print("=" * 50)
print("       STUDENT PERFORMANCE ANALYSIS")
print("=" * 50)

print("\nMarks of Students:")
print(marks)

print("\nStudent Averages:")
for i, average in enumerate(student_averages):
    print(f"Student {i + 1}: {average:.2f}")

print("\nSubject Averages:")
for i, average in enumerate(subject_averages):
    print(f"Subject {i + 1}: {average:.2f}")

print("\nStudent with Highest Average:")
print(f"Student {highest_student + 1} - {student_averages[highest_student]:.2f}")

print("\nStudent with Lowest Average:")
print(f"Student {lowest_student + 1} - {student_averages[lowest_student]:.2f}")

print("\nHighest Mark in Entire Dataset:")
print(highest_mark)

print("\nLowest Mark in Entire Dataset:")
print(lowest_mark)

print("\nNumber of Students with Average Above 75:")
print(students_above_75)

print("\nAll Marks Greater Than 90:")
print(marks_above_90)

print("\nFinal Student Information:")
print("-" * 50)
print(f"{'Student':<10}{'Average':<15}{'Grade':<10}")
print("-" * 50)

for student in student_information:
    print(
        f"{student['student']:<10}"
        f"{student['average']:<15.2f}"
        f"{student['grade']:<10}"
    )

print("-" * 50)

       STUDENT PERFORMANCE ANALYSIS

Marks of Students:
[[ 26  31  48  37]
 [ 14 100  27  21]
 [ 80  16  69  66]
 [ 99  40  25  30]
 [ 76  97  47  29]
 [ 68  35  91  83]
 [ 70  57 100  55]
 [ 51  15   7  93]
 [ 63  49  40  51]
 [  8   6  84  15]]

Student Averages:
Student 1: 35.50
Student 2: 40.50
Student 3: 57.75
Student 4: 48.50
Student 5: 62.25
Student 6: 69.25
Student 7: 70.50
Student 8: 41.50
Student 9: 50.75
Student 10: 28.25

Subject Averages:
Subject 1: 55.50
Subject 2: 44.60
Subject 3: 53.80
Subject 4: 48.00

Student with Highest Average:
Student 7 - 70.50

Student with Lowest Average:
Student 10 - 28.25

Highest Mark in Entire Dataset:
100

Lowest Mark in Entire Dataset:
6

Number of Students with Average Above 75:
0

All Marks Greater Than 90:
[100  99  97  91 100  93]

Final Student Information:
--------------------------------------------------
Student   Average        Grade     
--------------------------------------------------
1         35.50          F         
2     